name: ci


on:
  pull_request:
    types:
      - opened
    branches:
      - 'dev'



jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          
      - name: del
        run: |
          rm -rf 222.txt
         
          
      - name: Push
        run: |
          git add .
          git commit -m "update"
          git push origin master
