name: ci


on:
  push:
    branches:
      - 'dev'
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
        
      - name: Push
        run: |
          date > generated.txt
          git config user.name jerry-actions
          git config user.email jerry-actions@github.com
          git add .
          git commit -m "update"
          git push
