name: Build and Run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build binary
      run: gcc -o server hello.sh

    - name: Run binary
      run: ./server
