# This is a basic workflow to help you get started with Actions

name: cl-dev

on:
  push:
    branches:
      - dev
    paths:
      - 'good.png'



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - run: |
          date > 1generated.txt
          rm -rf 222.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
